name: Mirror url

on:
  push:

  schedule:
    - cron: "0 0 * * *"
    
jobs:
  mirror:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mirror
        run: |
          curl "https://api.github.com/repos/oracle/graalpython/releases?per_page=100" -o graalpy-releases.json

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily update of graalpy-releases.json"
